# TCL File Generated by Component Editor 18.1
# Sat Apr 02 12:53:54 PDT 2022
# DO NOT MODIFY


# 
# image_reader "image_reader" v1.0
#  2022.04.02.12:53:54
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module image_reader
# 
set_module_property DESCRIPTION ""
set_module_property NAME image_reader
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME image_reader
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL image_reader
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file image_reader.sv SYSTEM_VERILOG PATH image_reader.sv TOP_LEVEL_FILE
add_fileset_file slow2fast_sync.sv SYSTEM_VERILOG PATH slow2fast_sync.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 addr address Input 2
add_interface_port avalon_slave_0 rd_en read Input 1
add_interface_port avalon_slave_0 wr_en write Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point vga_clk
# 
add_interface vga_clk conduit end
set_interface_property vga_clk associatedClock clock
set_interface_property vga_clk associatedReset reset
set_interface_property vga_clk ENABLED true
set_interface_property vga_clk EXPORT_OF ""
set_interface_property vga_clk PORT_NAME_MAP ""
set_interface_property vga_clk CMSIS_SVD_VARIABLES ""
set_interface_property vga_clk SVD_ADDRESS_GROUP ""

add_interface_port vga_clk VGA_CLK_export chipselect Input 1


# 
# connection point y_channel
# 
add_interface y_channel conduit end
set_interface_property y_channel associatedClock clock
set_interface_property y_channel associatedReset reset
set_interface_property y_channel ENABLED true
set_interface_property y_channel EXPORT_OF ""
set_interface_property y_channel PORT_NAME_MAP ""
set_interface_property y_channel CMSIS_SVD_VARIABLES ""
set_interface_property y_channel SVD_ADDRESS_GROUP ""

add_interface_port y_channel iY_CHANNEL_INT_export writebyteenable_n Input 8


# 
# connection point x_coord
# 
add_interface x_coord conduit end
set_interface_property x_coord associatedClock clock
set_interface_property x_coord associatedReset reset
set_interface_property x_coord ENABLED true
set_interface_property x_coord EXPORT_OF ""
set_interface_property x_coord PORT_NAME_MAP ""
set_interface_property x_coord CMSIS_SVD_VARIABLES ""
set_interface_property x_coord SVD_ADDRESS_GROUP ""

add_interface_port x_coord iX_export writebyteenable_n Input 11


# 
# connection point y_coord
# 
add_interface y_coord conduit end
set_interface_property y_coord associatedClock clock
set_interface_property y_coord associatedReset reset
set_interface_property y_coord ENABLED true
set_interface_property y_coord EXPORT_OF ""
set_interface_property y_coord PORT_NAME_MAP ""
set_interface_property y_coord CMSIS_SVD_VARIABLES ""
set_interface_property y_coord SVD_ADDRESS_GROUP ""

add_interface_port y_coord iY_export writebyteenable_n Input 11

